### ISSUE TITLE
serde is not an optional dependency

### ISSUE THREAD

**Issue by DSPOM2** [rust-analyzer/smol_str#42]
Judging from how the Cargo.toml is written, I assumed that serde was supposed to be an optional dependency.
However, when inspecting cargo bloat for my project (which uses smol_str) I noticed a long compile time for serde.
I was able to reproduce with an empty project (just an empty src/lib.rs file):

``` toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"
[dependencies]
smol_str = "0.1.21"
```

Running `cargo check` shows that serde is compiled and running cargo bloat yields

``` shell
> cargo bloat --time -j 1
Time Crate
3.20s serde
0.39s smol_str
```

Just as an example for my larger project, serde is still among the top 7 contributors even tough I am not using it at all (and according to cargo tree only depend upon it trough smol_str).

``` shell
> cargo bloat --time -j 1
 Time Crate
9.99s syn
9.93s hir_def
5.41s rowan
4.40s basedb
3.59s logos_derive
3.49s regex_syntax
3.10s serde
...
```

I am using the latest stable version (rust 1.56.1 on linux/nixos). Is there any way to remove the serde dependency or am I missing something?

**Comment by lnicola** [comment]
That's probably because of:

```toml
default = ["std"]
std = ["serde/std"]
```

You can try setting `default_features = false` on `smol_str`.
